### PR TITLE
Ruler should following point second try

### PR DESCRIPTION
**Pull request by valerii-cognite**
There was the problem that ruler started follow the point only after second update

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-101.surge.sh

**Comment by evancharlton** [comment]
Same comment as on #100 -- how do I (and future readers) test this?

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-101.surge.sh

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-101.surge.sh

**Pull request merged**
