### PR TITLE
Ruler touch behavior should differ from hover

### PR DESCRIPTION
**Pull request by valerii-cognite**
To reproduce navigate to 'Live loading and ruler' story. By clicking or touching the chart, ruler should stick with the selected point during live loading. By dragging the chart ruler should stay on the same x position.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-102.surge.sh

**Comment by evancharlton** [comment]
On my computer, when I put it in touch mode, I can click ("touch") and the ruler sticks, but then I can't drag the chart, even after zooming in. Is this intentional?

**Comment by valerii-cognite** [comment]
Have you tried to zoom in first?

**Comment by evancharlton** [comment]
Same thing. Also, when I zoom in, the ruler suddenly appears, even though it didn't before I zoomed.

**Comment by valerii-cognite** [comment]
Hm, works fine for me both on computer and iOS in terms of zooming and dragging. Will check tomorrow morning

> Also, when I zoom in, the ruler suddenly appears, even though it didn't before I zoomed.

This one unexpected, but already took place before this PR.

**Pull request merged**
