### PR TITLE
Add possibility to pass subDomain to DataProvider

### PR DESCRIPTION
**Pull request by valerii-cognite**
Fix https://github.com/cognitedata/griff-react/issues/54

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-80.surge.sh

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-80.surge.sh

**Comment by evancharlton** [comment]
Be sure to note that this fixes #54 (right?)

**Comment by valerii-cognite** [comment]
Even better, just added seamless subDomain update

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-80.surge.sh

**Pull request merged**
