### PR TITLE
Use a prettier collapsed y axis

### PR DESCRIPTION
**Pull request by evancharlton**
Change the data-agnostic y axis to three vertical grayscale bars.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-91.surge.sh

**Comment by evancharlton** [comment]
@hamzaque I should point out that this is separate from the per-axis hover mode (that's #87) so the stories will be a bit weird to interact with. However, this is all about the look of the axis, not the behavior.

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-91.surge.sh

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-91.surge.sh

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-91.surge.sh

**Pull request merged**
