### PR TITLE
Using numeral dumb formatting for numbers.

### PR DESCRIPTION
**Pull request by martincognite**
An example of a temporary solution for #111 . Using max 3 decimals and uses the `k`, `m` and `b` notation for large numbers.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-150.surge.sh

**Comment by cognite-cicd** [comment]
[pr-server]
The storybook for this PR is hosted on https://griff-react-pr-150.surge.sh

**Comment by martincognite** [comment]
Not at all -- that's a lot smarter, I'll do that.

**Comment by evancharlton** [comment]
This can be closed (if #163 is approved & merged)

**Pull request closed without merging**
